export type AppLanguage = "pt" | "es" | "en";

export const pageCopy = {
  pt: {
    auth: { welcome:"Bem-vindo de volta",create:"Crie sua conta",signin:"Entrar na byTrust",createAccount:"Criar conta",continue:"Continue verificando produtos.",join:"Junte-se ao movimento.",name:"Nome",yourName:"Seu nome",username:"Nome de usuário",email:"E-mail",password:"Senha",hide:"Ocultar senha",show:"Mostrar senha",forgot:"Esqueci minha senha",wait:"Aguarde…",enter:"Entrar →",register:"Criar conta →",noAccount:"Não tem conta?",signup:"Cadastre-se",hasAccount:"Já tem conta?",requiredUser:"Nome de usuário é obrigatório.",shortPassword:"A senha deve ter pelo menos 8 caracteres.",unknown:"Erro desconhecido",sideTitle:"Protegendo sua confiança, produto por produto",sideText:"Junte-se à comunidade antifalsificação. Verifique, colecione selos e inspire outras pessoas.",stamp:"Onde a autenticidade vira certeza." },
    contact:{eyebrow:"Fale com a gente",title:"Vamos conversar?",text:"Quer integrar a API, virar parceiro ou tirar uma dúvida? Respondemos rapidamente.",email:"E-mail",phone:"Telefone",office:"Sede",location:"São Paulo · SP · Brasil",sent:"Mensagem enviada!",sentText:"Nosso time entra em contato em até 1 dia útil.",name:"Nome",company:"Empresa (opcional)",subject:"Assunto",message:"Mensagem",send:"Enviar mensagem",subjects:["Integração da API","Parceria de marca","Suporte ao consumidor","Imprensa"]},
    feed:{eyebrow:"Comunidade",title:"Feed",text:"Compartilhe e inspire outras pessoas a consumir com consciência.",placeholder:"Compartilhe sua experiência com produtos originais...",shortcut:"⌘ + Enter para publicar",publish:"Publicar",publishing:"Publicando…",empty:"Nenhuma publicação ainda.",first:"Seja o primeiro a compartilhar!",verified:"verificado",delete:"Excluir publicação",seal:"Selo",error:"Erro ao publicar"},
    guides:{eyebrow:"📘 Cartilhas byTrust",title:"Baixe nossos guias completos",text:"Material educativo gratuito para consumidores, lojistas, marcas e desenvolvedores.",download:"Baixar PDF",items:[["10 sinais de um produto falso","Guia rápido com checklist visual para identificar falsificações no ato da compra."],["Qual o problema da falsificação?","Impactos econômicos, riscos à saúde e consequências para consumidores e marcas."],["Cartilha do consumidor consciente","Como comprar online com segurança e usar a API byTrust no dia a dia."],["Onde a falsificação está presente?","Setores mais afetados pela pirataria e como ela se infiltra em diferentes mercados."],["Falsificações em cosméticos","Como reconhecer perfumes, maquiagens e dermocosméticos piratas."],["Por que comprar original?","Os riscos de produtos falsificados e os benefícios de escolher o original."]]},
    verify:{eyebrow:"Autenticidade em tempo real",title:"Verificar produto",text:"Tire uma foto, escolha o produto e confirme a autenticidade em segundos.",login:"Entre na sua conta",loginSuffix:"para verificar e receber selos.",photo:"Foto do produto *",choosePhoto:"Clique para selecionar uma foto",formats:"JPG, PNG ou WEBP · máx. 10 MB",product:"Produto *",loadingProducts:"Carregando produtos…",selectProduct:"Selecione o produto...",serial:"Código serial",optional:"(opcional)",serialExample:"Ex.: ABC12345",checking:"Verificando…",check:"Verificar autenticidade",original:"Produto Original ✓",suspicious:"Produto Suspeito ✕",sealPage:"Ver página do selo",share:"Compartilhar",copy:"Copiar link",achievement:"Nova conquista desbloqueada!",photoRequired:"Selecione uma foto do produto.",productRequired:"Selecione o produto.",formatError:"Formato não suportado. Use JPG, PNG ou WEBP.",sizeError:"A imagem deve ter no máximo 10 MB.",duplicate:"Você já verificou este produto com este serial. Tente um código diferente."},
    profile:{profile:"Perfil",authentic:"Autênticos",achievements:"Conquistas",checks:"Verificações",tabs:["Verificações","Selos","Conquistas"],noChecks:"Nenhuma verificação ainda.",noSeals:"Nenhum selo emitido ainda.",start:"Verifique um produto para começar.",checkNow:"Verificar agora",viewSeal:"Ver selo",open:"Abrir",seal:"Selo"},
    forgot:{title:"Esqueci minha senha",text:"Sem problemas. Enviaremos um link para redefinir sua senha.",sent:"E-mail enviado!",sentText:"Enviamos um link de redefinição para",expires:"O link expira em 30 minutos.",spam:"Não recebeu? Verifique a caixa de spam ou solicite um novo link.",resend:"Reenviar e-mail",backLogin:"Voltar para o login",registered:"E-mail cadastrado",hint:"Insira o e-mail associado à sua conta.",sending:"Enviando…",send:"Enviar link de redefinição",remember:"Lembrou sua senha? Faça login",home:"Voltar para o início",connection:"Erro de conexão com o servidor. Tente novamente."},
    reset:{title:"Redefinir senha",text:"Escolha uma nova senha forte para sua conta.",new:"Nova senha *",confirm:"Confirmar nova senha *",repeat:"Repita a nova senha",match:"Senhas coincidem",noMatch:"Senhas não coincidem",resetting:"Redefinindo…",action:"Redefinir senha",success:"Senha redefinida!",successText:"Sua senha foi alterada com sucesso. Use a nova senha para acessar sua conta.",goLogin:"Ir para o login",back:"Voltar para o login",requirements:["Pelo menos 6 caracteres","Pelo menos uma letra","Pelo menos um número"],connection:"Erro de conexão com o servidor. Tente novamente."},
    legal:{updated:"Última atualização: 06 de junho de 2026",back:"Voltar para o início",privacyLabel:"🔒 Política de Privacidade",privacyTitle:"Política de Privacidade da byTrust",termsLabel:"📜 Termos de Uso",termsTitle:"Termos e Condições de Uso da byTrust"}
  },
  es: {
    auth:{welcome:"Bienvenido de nuevo",create:"Crea tu cuenta",signin:"Entrar en byTrust",createAccount:"Crear cuenta",continue:"Continúa verificando productos.",join:"Únete al movimiento.",name:"Nombre",yourName:"Tu nombre",username:"Nombre de usuario",email:"Correo electrónico",password:"Contraseña",hide:"Ocultar contraseña",show:"Mostrar contraseña",forgot:"Olvidé mi contraseña",wait:"Espera…",enter:"Entrar →",register:"Crear cuenta →",noAccount:"¿No tienes cuenta?",signup:"Regístrate",hasAccount:"¿Ya tienes cuenta?",requiredUser:"El nombre de usuario es obligatorio.",shortPassword:"La contraseña debe tener al menos 8 caracteres.",unknown:"Error desconocido",sideTitle:"Protegiendo tu confianza, producto por producto",sideText:"Únete a la comunidad contra la falsificación. Verifica, colecciona sellos e inspira a otros.",stamp:"Donde la autenticidad se convierte en certeza."},
    contact:{eyebrow:"Habla con nosotros",title:"¿Conversamos?",text:"¿Quieres integrar la API, ser socio o resolver una duda? Respondemos rápidamente.",email:"Correo",phone:"Teléfono",office:"Sede",location:"São Paulo · SP · Brasil",sent:"¡Mensaje enviado!",sentText:"Nuestro equipo se pondrá en contacto en un día hábil.",name:"Nombre",company:"Empresa (opcional)",subject:"Asunto",message:"Mensaje",send:"Enviar mensaje",subjects:["Integración de API","Alianza de marca","Soporte al consumidor","Prensa"]},
    feed:{eyebrow:"Comunidad",title:"Feed",text:"Comparte e inspira a otros a consumir de forma consciente.",placeholder:"Comparte tu experiencia con productos originales...",shortcut:"⌘ + Enter para publicar",publish:"Publicar",publishing:"Publicando…",empty:"Aún no hay publicaciones.",first:"¡Sé el primero en compartir!",verified:"verificado",delete:"Eliminar publicación",seal:"Sello",error:"Error al publicar"},
    guides:{eyebrow:"📘 Guías byTrust",title:"Descarga nuestras guías completas",text:"Material educativo gratuito para consumidores, comercios, marcas y desarrolladores.",download:"Descargar PDF",items:[["10 señales de un producto falso","Lista visual rápida para identificar falsificaciones al comprar."],["¿Cuál es el problema de la falsificación?","Impactos económicos, riesgos para la salud y consecuencias para consumidores y marcas."],["Guía del consumidor consciente","Cómo comprar en línea con seguridad y usar byTrust a diario."],["¿Dónde está presente la falsificación?","Sectores más afectados y cómo la piratería entra en distintos mercados."],["Falsificaciones en cosméticos","Cómo reconocer perfumes, maquillaje y dermocosméticos falsos."],["¿Por qué comprar original?","Riesgos de los productos falsificados y beneficios del original."]]},
    verify:{eyebrow:"Autenticidad en tiempo real",title:"Verificar producto",text:"Toma una foto, elige el producto y confirma su autenticidad en segundos.",login:"Entra en tu cuenta",loginSuffix:"para verificar y recibir sellos.",photo:"Foto del producto *",choosePhoto:"Haz clic para seleccionar una foto",formats:"JPG, PNG o WEBP · máx. 10 MB",product:"Producto *",loadingProducts:"Cargando productos…",selectProduct:"Selecciona el producto...",serial:"Código de serie",optional:"(opcional)",serialExample:"Ej.: ABC12345",checking:"Verificando…",check:"Verificar autenticidad",original:"Producto Original ✓",suspicious:"Producto Sospechoso ✕",sealPage:"Ver página del sello",share:"Compartir",copy:"Copiar enlace",achievement:"¡Nuevo logro desbloqueado!",photoRequired:"Selecciona una foto del producto.",productRequired:"Selecciona el producto.",formatError:"Formato no compatible. Usa JPG, PNG o WEBP.",sizeError:"La imagen debe tener como máximo 10 MB.",duplicate:"Ya verificaste este producto con este número. Prueba otro código."},
    profile:{profile:"Perfil",authentic:"Auténticos",achievements:"Logros",checks:"Verificaciones",tabs:["Verificaciones","Sellos","Logros"],noChecks:"Aún no hay verificaciones.",noSeals:"Aún no se emitieron sellos.",start:"Verifica un producto para comenzar.",checkNow:"Verificar ahora",viewSeal:"Ver sello",open:"Abrir",seal:"Sello"},
    forgot:{title:"Olvidé mi contraseña",text:"No hay problema. Te enviaremos un enlace para restablecerla.",sent:"¡Correo enviado!",sentText:"Enviamos un enlace de restablecimiento a",expires:"El enlace caduca en 30 minutos.",spam:"¿No llegó? Revisa spam o solicita un nuevo enlace.",resend:"Reenviar correo",backLogin:"Volver al inicio de sesión",registered:"Correo registrado",hint:"Introduce el correo asociado a tu cuenta.",sending:"Enviando…",send:"Enviar enlace",remember:"¿Recordaste tu contraseña? Inicia sesión",home:"Volver al inicio",connection:"Error de conexión con el servidor. Inténtalo de nuevo."},
    reset:{title:"Restablecer contraseña",text:"Elige una contraseña nueva y segura.",new:"Nueva contraseña *",confirm:"Confirmar nueva contraseña *",repeat:"Repite la nueva contraseña",match:"Las contraseñas coinciden",noMatch:"Las contraseñas no coinciden",resetting:"Restableciendo…",action:"Restablecer contraseña",success:"¡Contraseña restablecida!",successText:"Tu contraseña se cambió correctamente. Úsala para acceder a tu cuenta.",goLogin:"Ir al inicio de sesión",back:"Volver al inicio de sesión",requirements:["Al menos 6 caracteres","Al menos una letra","Al menos un número"],connection:"Error de conexión con el servidor. Inténtalo de nuevo."},
    legal:{updated:"Última actualización: 6 de junio de 2026",back:"Volver al inicio",privacyLabel:"🔒 Política de Privacidad",privacyTitle:"Política de Privacidad de byTrust",termsLabel:"📜 Términos de Uso",termsTitle:"Términos y Condiciones de Uso de byTrust"}
  },
  en: {
    auth:{welcome:"Welcome back",create:"Create your account",signin:"Sign in to byTrust",createAccount:"Create account",continue:"Keep verifying products.",join:"Join the movement.",name:"Name",yourName:"Your name",username:"Username",email:"Email",password:"Password",hide:"Hide password",show:"Show password",forgot:"Forgot my password",wait:"Please wait…",enter:"Sign in →",register:"Create account →",noAccount:"No account yet?",signup:"Sign up",hasAccount:"Already have an account?",requiredUser:"Username is required.",shortPassword:"Password must be at least 8 characters.",unknown:"Unknown error",sideTitle:"Protecting your trust, one product at a time",sideText:"Join the anti-counterfeiting community. Verify, collect seals, and inspire others.",stamp:"Where authenticity becomes certainty."},
    contact:{eyebrow:"Talk to us",title:"Let's talk",text:"Want to integrate the API, become a partner, or ask a question? We respond quickly.",email:"Email",phone:"Phone",office:"Office",location:"São Paulo · SP · Brazil",sent:"Message sent!",sentText:"Our team will contact you within one business day.",name:"Name",company:"Company (optional)",subject:"Subject",message:"Message",send:"Send message",subjects:["API integration","Brand partnership","Consumer support","Press"]},
    feed:{eyebrow:"Community",title:"Feed",text:"Share and inspire others to consume consciously.",placeholder:"Share your experience with genuine products...",shortcut:"⌘ + Enter to post",publish:"Post",publishing:"Posting…",empty:"No posts yet.",first:"Be the first to share!",verified:"verified",delete:"Delete post",seal:"Seal",error:"Unable to post"},
    guides:{eyebrow:"📘 byTrust Guides",title:"Download our complete guides",text:"Free educational material for consumers, retailers, brands, and developers.",download:"Download PDF",items:[["10 signs of a counterfeit product","A quick visual checklist to identify counterfeits when buying."],["Why is counterfeiting a problem?","Economic impacts, health risks, and consequences for consumers and brands."],["Conscious consumer guide","How to shop online safely and use byTrust every day."],["Where is counterfeiting present?","The most affected industries and how piracy enters different markets."],["Counterfeit cosmetics","How to identify fake perfumes, makeup, and skincare products."],["Why buy genuine?","The risks of counterfeits and the benefits of choosing genuine products."]]},
    verify:{eyebrow:"Real-time authenticity",title:"Verify product",text:"Take a photo, choose the product, and confirm authenticity in seconds.",login:"Sign in to your account",loginSuffix:"to verify products and receive seals.",photo:"Product photo *",choosePhoto:"Click to select a photo",formats:"JPG, PNG, or WEBP · max. 10 MB",product:"Product *",loadingProducts:"Loading products…",selectProduct:"Select the product...",serial:"Serial code",optional:"(optional)",serialExample:"E.g. ABC12345",checking:"Verifying…",check:"Verify authenticity",original:"Genuine Product ✓",suspicious:"Suspicious Product ✕",sealPage:"View seal page",share:"Share",copy:"Copy link",achievement:"New achievement unlocked!",photoRequired:"Select a product photo.",productRequired:"Select a product.",formatError:"Unsupported format. Use JPG, PNG, or WEBP.",sizeError:"The image must be no larger than 10 MB.",duplicate:"You already verified this product with this serial number. Try a different code."},
    profile:{profile:"Profile",authentic:"Genuine",achievements:"Achievements",checks:"Verifications",tabs:["Verifications","Seals","Achievements"],noChecks:"No verifications yet.",noSeals:"No seals issued yet.",start:"Verify a product to get started.",checkNow:"Verify now",viewSeal:"View seal",open:"Open",seal:"Seal"},
    forgot:{title:"Forgot my password",text:"No problem. We'll send you a link to reset it.",sent:"Email sent!",sentText:"We sent a reset link to",expires:"The link expires in 30 minutes.",spam:"Didn't receive it? Check spam or request a new link.",resend:"Resend email",backLogin:"Back to sign in",registered:"Registered email",hint:"Enter the email associated with your account.",sending:"Sending…",send:"Send reset link",remember:"Remembered your password? Sign in",home:"Back to home",connection:"Unable to connect to the server. Try again."},
    reset:{title:"Reset password",text:"Choose a strong new password for your account.",new:"New password *",confirm:"Confirm new password *",repeat:"Repeat the new password",match:"Passwords match",noMatch:"Passwords do not match",resetting:"Resetting…",action:"Reset password",success:"Password reset!",successText:"Your password was changed successfully. Use it to access your account.",goLogin:"Go to sign in",back:"Back to sign in",requirements:["At least 6 characters","At least one letter","At least one number"],connection:"Unable to connect to the server. Try again."},
    legal:{updated:"Last updated: June 6, 2026",back:"Back to home",privacyLabel:"🔒 Privacy Policy",privacyTitle:"byTrust Privacy Policy",termsLabel:"📜 Terms of Use",termsTitle:"byTrust Terms and Conditions of Use"}
  }
} as const;

export function getPageCopy(language?: string) {
  const code = language?.split("-")[0] as AppLanguage;
  return pageCopy[code] ?? pageCopy.pt;
}
