import { useState, useEffect } from "react";
import { useNavigate, Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { ShieldCheck, Eye, EyeOff, Loader2 } from "lucide-react";
import { useAuth } from "../hooks/useAuth";
import { getPageCopy } from "../locales/pageCopy";

export default function Auth(){const {user,login,register,loading}=useAuth();const nav=useNavigate();const {i18n}=useTranslation();const c=getPageCopy(i18n.language).auth;const [mode,setMode]=useState<"login"|"register">("login");const [show,setShow]=useState(false);const [err,setErr]=useState("");const [f,setF]=useState({email:"",username:"",password:"",displayName:""});useEffect(()=>{if(user)nav("/verificar",{replace:true})},[user,nav]);const set=(k:keyof typeof f)=>(e:React.ChangeEvent<HTMLInputElement>)=>setF(x=>({...x,[k]:e.target.value}));
const submit=async()=>{setErr("");try{if(mode==="login")await login(f.email,f.password);else{if(!f.username.trim()){setErr(c.requiredUser);return}if(f.password.length<8){setErr(c.shortPassword);return}await register(f.email,f.username,f.password,f.displayName||undefined)}nav("/verificar",{replace:true})}catch(e){setErr(e instanceof Error?e.message:c.unknown)}};
return <div className="min-h-screen flex fade-up"><aside className="hidden lg:flex flex-col justify-between w-96 bg-ink-900 p-12 text-cream-100 shrink-0"><div className="flex items-center gap-2.5"><div className="w-8 h-8 rounded-full bg-cream-100 flex items-center justify-center"><ShieldCheck size={16} className="text-ink-900"/></div><span className="font-serif font-bold text-lg">by<em className="not-italic text-gold-400">Trust</em>.</span></div><div><h2 className="font-serif font-black text-4xl leading-tight mb-4">{c.sideTitle}</h2><p className="text-cream-300 text-sm leading-relaxed">{c.sideText}</p></div><div className="stamp text-cream-200 border-cream-300">{c.stamp}</div></aside>
<main className="flex-1 flex items-center justify-center px-6 py-24"><div className="w-full max-w-sm"><div className="mb-8"><p className="section-label mb-2">{mode==="login"?c.welcome:c.create}</p><h1 className="font-serif font-black text-3xl">{mode==="login"?c.signin:c.createAccount}</h1><p className="text-ink-500 text-sm mt-2">{mode==="login"?c.continue:c.join}</p></div><div className="space-y-4">{mode==="register"&&<><Field label={c.name} placeholder={c.yourName} value={f.displayName} onChange={set("displayName")}/><Field label={`${c.username} *`} value={f.username} onChange={set("username")}/></>}<Field label={`${c.email} *`} type="email" value={f.email} onChange={set("email")}/><div><label className="label">{c.password} *</label><div className="relative"><input type={show?"text":"password"} value={f.password} onChange={set("password")} onKeyDown={e=>e.key==="Enter"&&submit()} className="input pr-11"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2" aria-label={show?c.hide:c.show}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>{mode==="login"&&<div className="text-right mt-1"><Link to="/esqueci-senha" className="text-xs underline">{c.forgot}</Link></div>}</div>{err&&<div className="text-sm text-red-700 bg-red-50 border border-red-200 rounded-xl px-4 py-3">{err}</div>}<button onClick={submit} disabled={loading} className="btn-primary w-full justify-center py-3">{loading?<><Loader2 size={16} className="animate-spin"/> {c.wait}</>:mode==="login"?c.enter:c.register}</button><p className="text-center text-sm text-ink-500">{mode==="login"?<>{c.noAccount} <button onClick={()=>{setMode("register");setErr("")}} className="font-semibold underline">{c.signup}</button></>:<>{c.hasAccount} <button onClick={()=>{setMode("login");setErr("")}} className="font-semibold underline">{c.enter.replace(" →","")}</button></>}</p></div></div></main></div>}
function Field({label,...rest}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <div><label className="label">{label}</label><input className="input" {...rest}/></div>}
