import { useState, useEffect } from "react";
import { useTranslation } from "react-i18next";
import { Loader2, Send, Trash2, ShieldCheck } from "lucide-react";
import { api, type Post } from "../lib/api";
import { useAuth } from "../hooks/useAuth";
import { getPageCopy } from "../locales/pageCopy";

export default function Feed(){const {user}=useAuth();const {i18n}=useTranslation();const c=getPageCopy(i18n.language).feed;const [posts,setPosts]=useState<Post[]>([]);const [loading,setLoading]=useState(true);const [loadErr,setLoadErr]=useState("");const [text,setText]=useState("");const [posting,setPosting]=useState(false);const [postErr,setPostErr]=useState("");
  const load=()=>api.community.feed().then(setPosts).catch((e:Error)=>setLoadErr(e.message)).finally(()=>setLoading(false));useEffect(()=>{load()},[]);
  const submit=async()=>{if(!text.trim())return;setPostErr("");setPosting(true);try{const p=await api.community.post(text.trim());setPosts(x=>[p,...x]);setText("")}catch(e){setPostErr(e instanceof Error?e.message:c.error)}finally{setPosting(false)}};
  const del=async(id:string)=>{await api.community.delete(id);setPosts(x=>x.filter(p=>p.id!==id))};
  return <div className="max-w-2xl mx-auto px-4 pt-32 pb-20 fade-up"><div className="mb-10"><p className="section-label mb-2">{c.eyebrow}</p><h1 className="font-serif font-black text-5xl">{c.title}</h1><p className="text-ink-500 mt-2 text-sm">{c.text}</p></div>
  {user&&<div className="card mb-8"><div className="flex gap-3"><div className="w-9 h-9 rounded-full bg-gold-500/10 grid place-items-center font-bold text-gold-600">{(user.displayName??user.username)[0].toUpperCase()}</div><div className="flex-1"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={c.placeholder} className="w-full bg-transparent resize-none text-sm focus:outline-none min-h-20" onKeyDown={e=>{if(e.key==="Enter"&&e.metaKey)submit()}}/>{postErr&&<p className="text-xs text-red-600">{postErr}</p>}<div className="flex justify-between mt-3 pt-3 border-t border-ink-100"><span className="text-xs text-ink-400">{c.shortcut}</span><button onClick={submit} disabled={posting||!text.trim()} className="btn-primary text-sm py-2 px-5">{posting?<Loader2 size={14} className="animate-spin"/>:<Send size={14}/>} {posting?c.publishing:c.publish}</button></div></div></div></div>}
  {loading?<div className="flex justify-center py-20"><Loader2 className="animate-spin text-ink-400"/></div>:loadErr?<div className="text-center py-20 text-red-600">{loadErr}</div>:posts.length===0?<div className="text-center py-20"><p className="font-serif text-xl font-bold">{c.empty}</p><p className="text-sm text-ink-400">{c.first}</p></div>:<div className="space-y-4">{posts.map(p=><div key={p.id} className="card"><div className="flex justify-between mb-4"><div><strong className="text-sm">{p.user.displayName??p.user.username}</strong><div className="text-xs text-ink-400">{new Date(p.createdAt).toLocaleDateString(i18n.language)}</div></div><div className="flex gap-2">{p.isAuto&&<span className="tag-green"><ShieldCheck size={10}/> {c.verified}</span>}{user?.username===p.user.username&&<button onClick={()=>del(p.id)} aria-label={c.delete}><Trash2 size={14}/></button>}</div></div><p className="text-sm text-ink-700">{p.content}</p>{p.imageUrl&&<img src={p.imageUrl} alt={c.seal} className="w-full rounded-xl border mt-4"/>}</div>)}</div>}</div>;
}
